### ISSUE TITLE
Signature of AndroidTransloadit::newAssembly should be updated (Context instead of Activity) to enable uploads through services and workers

### ISSUE THREAD

**Issue by patricks-dev** [transloadit/android-sdk#15]
I'm pretty sure the method can be implemented using only the application context (a Context object, which is a superclass of Activity).

Current signature:
`public AndroidAsyncAssembly newAssembly(com.transloadit.sdk.async.AssemblyProgressListener listener, android.app.Activity activity);`

Desired signature:
`public AndroidAsyncAssembly newAssembly(com.transloadit.sdk.async.AssemblyProgressListener listener, android.content.Context context);`

Having to provide an Activity is really problematic, as activities are only available when the user is interacting with the app. Therefore I cannot provide an activity from a worker, which I'd like to use in order to offer my users a delayed upload (so they can select their files offline and have the worker upload them afterward when they are back online). I cannot provide an activity either from a service, from which I handle failed downloads (and from which I'd also like to handle failed uploads).

**Comment by cdr-chakotay** [comment]
Hi @patricks-dev :) 

Thank you for the feedback! We will discuss your issue internally and I will come back to you!

**Comment by Acconut** [comment]
I don't see anything speaking against this and we have done a similar change for tus-android-client in the past. @patricks-dev or @cdr-chakotay would you be able to open a PR for this?

**Comment by cdr-chakotay** [comment]
Sure, will do as soon as I will come to that. Probably until Monday :)

**Comment by cdr-chakotay** [comment]
Will be part of the next release @patricks-dev .

Shall we issue a release extra for that @Acconut ?

**Comment by Acconut** [comment]
Thank you for the release, @cdr-chakotay!
