### ISSUE TITLE
Issues brought up on Intercom

### ISSUE THREAD

**Issue by CharlieMacnamara** [transloadit/android-sdk#4]
1) ~~AssemblyResponse::getId throws exceptions instead of doing its job because it looks for "id" instead of ”assembly_id.”~~
2) Submitting an assembly requires an Activity when a Context should be enough. In my case, I use a service for managing the uploads: having to provide an activity really feels like a hack.
3) The upload progress is not updated frequently enough to use it to update a progress bar properly.

Additional feature request:
Upload progress and completion/failure callbacks for individual uploads.

**Comment by Acconut** [comment]
Number 1 and 2 should be easy to implement.

Number 3 would likely take some more work in the tus-java-client, which the android-sdk uses internally.

> Upload progress and completion/failure callbacks for individual uploads.

I do not think we have something similar in any other SDK. Maybe it's worth discussing if we want to offer this in all or none SDKs.

**Comment by cdr-chakotay** [comment]
Let's discuss this at some point @Acconut

**Comment by CharlieMacnamara** [comment]
Hey guys,

Hope all is well. Please remove me from this thread. :)

All the best,
Charlie

**Comment by cdr-chakotay** [comment]
Hi Charlie, 

you are the author of this issue. I think deleting is not possible. I will close this issue now.
